feat: upgrade minimum php version
TransbankDevelopers/transbank-sdk-php pull request #285
Opened 2024-07-01 13:36 UTC by gasspper

- the minimum version of php was raised to 8.2
- all variables were typed in the sdk

2024-07-02 20:22 UTC, mastudillot requested changes
Check my comments

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/Options.php
> +    public string $integrationType = self::ENVIRONMENT_INTEGRATION;
remove value or set to null

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/TransaccionCompleta/Responses/MallTransactionInstallmentsResponse.php
> +    public function getIdQueryInstallments(): string
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/TransaccionCompleta/Responses/MallTransactionInstallmentsResponse.php
> +    public function getDeferredPeriods(): array
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/PatpassComercio/Responses/InscriptionFinishResponse.php
> +    public function getStatus(): string
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/TransaccionCompleta/Responses/MallTransactionStatusResponse.php
>      }
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/TransaccionCompleta/Responses/TransactionCreateResponse.php
> +    public function getToken(): string
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/TransaccionCompleta/Responses/TransactionInstallmentsResponse.php
> +    public function getDeferredPeriods(): array
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/TransaccionCompleta/Responses/TransactionRefundResponse.php
> +    public function getType(): string
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/WebpayPlus/Responses/MallTransactionStatusResponse.php
> +    public function getBuyOrder(): string
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/WebpayPlus/Responses/MallTransactionStatusResponse.php
> +    public function getAccountingDate(): string
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/WebpayPlus/Responses/MallTransactionStatusResponse.php
> +    public function getTransactionDate(): string
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/WebpayPlus/Responses/MallTransactionStatusResponse.php
> +    public function getVci(): string
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/WebpayPlus/Responses/TransactionCaptureResponse.php
> +    public function getResponseCode(): int
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/WebpayPlus/Responses/TransactionRefundResponse.php
> +    public function getResponseCode(): int
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/WebpayPlus/Responses/TransactionRefundResponse.php
> +    public function getType(): string
add `?` in return

2024-07-02 20:22 UTC, mastudillot commented on src/Webpay/WebpayPlus/Responses/TransactionStatusResponse.php
> +    public function getVci(): string
add `?` in return

2024-07-02 21:57 UTC, gasspper commented on src/Webpay/WebpayPlus/Responses/TransactionStatusResponse.php
> +    public function getVci(): string
done

2024-07-02 21:57 UTC, gasspper commented on src/Webpay/WebpayPlus/Responses/TransactionRefundResponse.php
> +    public function getType(): string
done

2024-07-02 21:57 UTC, gasspper commented on src/Webpay/WebpayPlus/Responses/TransactionRefundResponse.php
> +    public function getResponseCode(): int
done

2024-07-02 21:57 UTC, gasspper commented on src/Utils/RequestServiceTrait.php
> +    public function sendRequest(string $method, string $endpoint, array $payload = [])
done

2024-07-02 21:57 UTC, gasspper commented on src/Webpay/Options.php
> +    public string $integrationType = self::ENVIRONMENT_INTEGRATION;
done

2024-07-02 21:57 UTC, gasspper commented on src/Webpay/TransaccionCompleta/Responses/MallTransactionInstallmentsResponse.php
> +    public function getIdQueryInstallments(): string
done

2024-07-02 21:58 UTC, gasspper commented on src/Webpay/TransaccionCompleta/Responses/MallTransactionInstallmentsResponse.php
> +    public function getDeferredPeriods(): array
done

2024-07-02 21:58 UTC, gasspper commented on src/PatpassComercio/Responses/InscriptionFinishResponse.php
> +    public function getStatus(): string
done

2024-07-02 21:58 UTC, gasspper commented on src/Webpay/TransaccionCompleta/Responses/MallTransactionStatusResponse.php
>      }
done

2024-07-02 21:58 UTC, gasspper commented on src/Webpay/TransaccionCompleta/Responses/TransactionInstallmentsResponse.php
> +    public function getDeferredPeriods(): array
done

2024-07-02 21:58 UTC, gasspper commented on src/Webpay/WebpayPlus/Responses/MallTransactionStatusResponse.php
> +    public function getBuyOrder(): string
done

2024-07-02 21:58 UTC, gasspper commented on src/Webpay/TransaccionCompleta/Responses/TransactionRefundResponse.php
> +    public function getType(): string
done

2024-07-02 21:58 UTC, gasspper commented on src/Webpay/WebpayPlus/Responses/MallTransactionStatusResponse.php
> +    public function getAccountingDate(): string
done

2024-07-02 21:58 UTC, gasspper commented on src/Webpay/WebpayPlus/Responses/MallTransactionStatusResponse.php
> +    public function getTransactionDate(): string
done

2024-07-02 21:58 UTC, gasspper commented on src/Webpay/WebpayPlus/Responses/MallTransactionStatusResponse.php
> +    public function getVci(): string
done

2024-07-02 21:58 UTC, gasspper commented on src/Webpay/WebpayPlus/Responses/TransactionCaptureResponse.php
> +    public function getResponseCode(): int
done

2024-07-02 21:58 UTC, gasspper commented on src/Webpay/TransaccionCompleta/Responses/TransactionCreateResponse.php
> +    public function getToken(): string
done

2024-07-03 20:19 UTC, Matiasnickolas approved these changes
LGTM 🤙

2024-07-03 21:05 UTC, tribiec approved these changes
GJ 🚀

2024-07-03 21:20 UTC, tribiec approved these changes

2024-07-03 21:23 UTC, Matiasnickolas approved these changes
LGTM 🌝

2024-07-03 21:26 UTC, merged